---
DataLoader:
  file_path: ./
  file_name: samples
Calculator:
  selected_columns: [live_fr_living_ctr, live_fr_living_lvtr, live_fr_living_gtr, fr_pvtr,]
  upper_bound_3sigma: 10
Objective:
  study_name: Make KS Great Again
  direction: maximize
  formula: -2 * targets[0] - targets[1]
Evaluator:
  flags: [portfolio, portfolio]
  target_columns: [live_click, ua_count]
